basePath: /v1
definitions:
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.testResponse:
    type: object
host: localhost:8080
info:
  contact: {}
  description: Some service as an example
  title: Go Apichka
  version: "1.0"
paths:
  /test/hello:
    get:
      consumes:
      - application/json
      description: Show hello world
      operationId: testID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.testResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show hello world
      tags:
      - test
swagger: "2.0"
